pub const ExtismPointer = u64;
pub extern fn extism_input_length() u64;
pub extern fn extism_length(ExtismPointer) u64;
pub extern fn extism_alloc(u64) ExtismPointer;
pub extern fn extism_free(ExtismPointer) void;
pub extern fn extism_input_load_u8(ExtismPointer) u8;
pub extern fn extism_input_load_u64(ExtismPointer) u64;
pub extern fn extism_output_set(ExtismPointer, u64) void;
pub extern fn extism_error_set(ExtismPointer) void;
pub extern fn extism_config_get(ExtismPointer) ExtismPointer;
pub extern fn extism_var_get(ExtismPointer) ExtismPointer;
pub extern fn extism_var_set(ExtismPointer, ExtismPointer) void;
pub extern fn extism_store_u8(ExtismPointer, u8) void;
pub extern fn extism_load_u8(ExtismPointer) u8;
pub extern fn extism_store_u64(ExtismPointer, u64) void;
pub extern fn extism_load_u64(ExtismPointer) u64;
pub extern fn extism_http_request(ExtismPointer, ExtismPointer) ExtismPointer;
pub extern fn extism_http_status_code() i32;
pub extern fn extism_log_info(ExtismPointer) void;
pub extern fn extism_log_debug(ExtismPointer) void;
pub extern fn extism_log_warn(ExtismPointer) void;
pub extern fn extism_log_error(ExtismPointer) void;