pub const ExtismPointer = u64;
pub extern "extism:env" fn input_length() u64;
pub extern "extism:env" fn length(ExtismPointer) u64;
pub extern "extism:env" fn alloc(u64) ExtismPointer;
pub extern "extism:env" fn free(ExtismPointer) void;
pub extern "extism:env" fn input_load_u8(ExtismPointer) u8;
pub extern "extism:env" fn input_load_u64(ExtismPointer) u64;
pub extern "extism:env" fn output_set(ExtismPointer, u64) void;
pub extern "extism:env" fn error_set(ExtismPointer) void;
pub extern "extism:env" fn config_get(ExtismPointer) ExtismPointer;
pub extern "extism:env" fn var_get(ExtismPointer) ExtismPointer;
pub extern "extism:env" fn var_set(ExtismPointer, ExtismPointer) void;
pub extern "extism:env" fn store_u8(ExtismPointer, u8) void;
pub extern "extism:env" fn load_u8(ExtismPointer) u8;
pub extern "extism:env" fn store_u64(ExtismPointer, u64) void;
pub extern "extism:env" fn load_u64(ExtismPointer) u64;
pub extern "extism:env" fn http_request(ExtismPointer, ExtismPointer) ExtismPointer;
pub extern "extism:env" fn http_status_code() i32;
pub extern "extism:env" fn log_info(ExtismPointer) void;
pub extern "extism:env" fn log_debug(ExtismPointer) void;
pub extern "extism:env" fn log_warn(ExtismPointer) void;
pub extern "extism:env" fn log_error(ExtismPointer) void;
