pub const ExtismHandle = u64;
pub const ExtismStream = enum(u8) { Input, Output };
pub const ExtismLogLevel = enum(u8) { Error, Warn, Info, Debug, Trace };
pub extern "extism:host/env" fn read(ExtismStream, ExtismHandle) i64;
pub extern "extism:host/env" fn write(ExtismStream, ExtismHandle) i64;
pub extern "extism:host/env" fn close(ExtismStream) void;
pub extern "extism:host/env" fn bytes_remaining(ExtismStream) i64;
pub extern "extism:host/env" fn stack_push() void;
pub extern "extism:host/env" fn stack_pop() void;
pub extern "extism:host/env" fn @"error"(ExtismHandle) void;
pub extern "extism:host/env" fn log(ExtismLogLevel, ExtismHandle) void;
pub extern "extism:host/env" fn http_request(ExtismHandle, ExtismHandle) ExtismHandle;
pub extern "extism:host/env" fn http_status_code() i32;
pub extern "extism:host/env" fn http_body(ExtismHandle) i64;
pub extern "extism:host/env" fn config_read(ExtismHandle, ExtismHandle) i64;
pub extern "extism:host/env" fn config_length(ExtismHandle) i64;
